import { DragDropQuestions } from "../../../../components/DragDropQuestions/DragDropQuestions";

export const AtlanticCurrents = () => {
    const data = {
		questionsHaveImg: false,
		answersHaveImg: false,
		questions: [
			{
				id: "q1",
				title: "Iliq oqimlar",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#eb4d4b",
			},
			{
				id: "q2",
				title: "Sovuq oqimlar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#eb4d4b",
			},
			{
				id: "q3",
				title: "Iliq oqimlar",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#eb4d4b",
			},
			{
				id: "q4",
				title: "Sovuq oqimlar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#eb4d4b",
			},
			{
				id: "q5",
				title: "Iliq oqimlar",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#eb4d4b",
			},
			{
				id: "q6",
				title: "Sovuq oqimlar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#eb4d4b",
			},
			{
				id: "q7",
				title: "Iliq oqimlar",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#eb4d4b",
			},
			{
				id: "q8",
				title: "Sovuq oqimlar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#eb4d4b",
			},
			{
				id: "q9",
				title: "Iliq oqimlar",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#eb4d4b",
			},
			{
				id: "q10",
				title: "Sovuq oqimlar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#eb4d4b",
			},
			{
				id: "q11",
				title: "Iliq oqimlar",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#eb4d4b",
			},
			{
				id: "q12",
				title: "Sovuq oqimlar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#eb4d4b",
			},
			{
				id: "q13",
				title: "Iliq oqimlar",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#eb4d4b",
			},
			{
				id: "q14",
				title: "Sovuq oqimlar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#eb4d4b",
			},
		],
		answers: [
			{
				id: "a1",
				title: "Sharqiy Grenlandiya",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#686de0",
			},
			{
				id: "a2",
				title: "Labrador",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#686de0",
			},
			{
				id: "a3",
				title: "Folklend",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#686de0",
			},
			{
				id: "a4",
				title: "Florida",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#686de0",
			},
			{
				id: "a5",
				title: "Shimoliy Atlantika",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#686de0",
			},
			{
				id: "a6",
				title: "Golfstrim",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#686de0",
			},
			{
				id: "a7",
				title: "Kanar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#686de0",
			},
			{
				id: "a8",
				title: "Bengal",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#686de0",
			},
			{
				id: "a9",
				title: "Gvineya",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#686de0",
			},
			{
				id: "a10",
				title: "Braziliya",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#686de0",
			},
			{
				id: "a11",
				title: "G'arbiy Shamollar",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#686de0",
			},
			{
				id: "a12",
				title: "Antarktika",
				isImage: false,
				img: "",
				answer: "2",
				bgColor: "#686de0",
			},
			{
				id: "a13",
				title: "Shimoliy Passat",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#686de0",
			},
			{
				id: "a14",
				title: "Janubiy Passat",
				isImage: false,
				img: "",
				answer: "1",
				bgColor: "#686de0",
			},
		],
	};
    return <>
        <section>
            <div className="container">
                <DragDropQuestions data={data}/>
            </div>
        </section>
    </>
}
